# App info
name: smoke_signal

description: All the basic social media apps wrapped into one, built for users not investors.

publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Flutter (Google)
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.2.7
  path_provider: ^2.0.11
  shared_preferences: ^2.0.15
  google_fonts: ^4.0.3
  image_picker: ^0.8.5+3

  # Firebase (Google)
  firebase_core: ^2.3.0
  firebase_auth: ^4.1.4
  firebase_messaging: ^14.1.2
  cloud_firestore: ^4.1.0
  cloud_functions: ^4.0.10

  # Community
  flutter_colorpicker: ^1.0.3
  email_validator: ^2.1.17
  flutter_local_notifications: ^13.0.0
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Community
  flutter_launcher_icons: ^0.12.0

# App configuration
flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/app-icon.png
    - assets/dark-forest.png
    - assets/dusk-mountain.png
    - assets/loading.gif
    - assets/none.png
    - assets/smoke-signal.gif

flutter_icons:
  image_path: assets/app-icon.png
  adaptive_icon_foreground: assets/app-icon.png
  adaptive_icon_background: "#A520DA"
  android: true
  ios: true

flutter_native_splash:
  color: "#A520DA"
  image: assets/app-icon.png
