name: Check version number updates

on:
  pull_request:
    branches: [ main ]

jobs:
  version_check:
    runs-on: ubuntu-latest
    name: Verify all files that track the version were updated
    steps:
    - name: Versioning checker
      uses: empathictech/versioning-checker@2.1.6
      with:
        tracked_files: APP_VERSION,CHANGELOG.md,pubspec.yaml